name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: t3-1-new-1
      id: t3-1-new-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t3-1-new-1
        setup-command: ''
        command: gcc main.c -o main -lm && ./main
        input: |-
          2
          3
        expected-output: |-
          25
        comparison-method: exact
        timeout: 1
        max-score: 25
    - name: t3-1-new-2
      id: t3-1-new-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t3-1-new-2
        setup-command: ''
        command: gcc main.c -o main -lm && ./main
        input: |-
          -4
          1
        expected-output: |-
          9
        comparison-method: exact
        timeout: 1
        max-score: 25
    - name: t3-1-new-3
      id: t3-1-new-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t3-1-new-3
        setup-command: ''
        command: gcc main.c -o main -lm && ./main
        input: |-
          0
          0
        expected-output: |-
          0
        comparison-method: exact
        timeout: 1
        max-score: 25
    - name: t3-1-new-4
      id: t3-1-new-4
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t3-1-new-4
        setup-command: ''
        command: gcc main.c -o main -lm && ./main
        input: |-
          10
          15
        expected-output: |-
          625
        comparison-method: exact
        timeout: 1
        max-score: 25
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        T3-1-NEW-1_RESULTS: "${{steps.t3-1-new-1.outputs.result}}"
        T3-1-NEW-2_RESULTS: "${{steps.t3-1-new-2.outputs.result}}"
        T3-1-NEW-3_RESULTS: "${{steps.t3-1-new-3.outputs.result}}"
        T3-1-NEW-4_RESULTS: "${{steps.t3-1-new-4.outputs.result}}"
      with:
        runners: t3-1-new-1,t3-1-new-2,t3-1-new-3,t3-1-new-4