name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: t6-1-1
      id: t6-1-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t6-1-1
        setup-command: ''
        command: gcc main.c -o main -lm && ./main
        input: |-
          0
          2
        expected-output: |-
          200
        comparison-method: exact
        timeout: 1
        max-score: 25
    - name: t6-1-2
      id: t6-1-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t6-1-2
        setup-command: ''
        command: gcc main.c -o main -lm && ./main
        input: |-
          600
          1
        expected-output: |-
          400
        comparison-method: exact
        timeout: 1
        max-score: 25
    - name: t6-1-3
      id: t6-1-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t6-1-3
        setup-command: ''
        command: gcc main.c -o main -lm && ./main
        input: |-
          900
          1
        expected-output: |-
          500
        comparison-method: exact
        timeout: 1
        max-score: 25
    - name: t6-1-4
      id: t6-1-4
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t6-1-4
        setup-command: ''
        command: gcc main.c -o main -lm && ./main
        input: |-
          1500
          2
        expected-output: |-
          5200
        comparison-method: exact
        timeout: 1
        max-score: 25
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        T6-1-1_RESULTS: "${{steps.t6-1-1.outputs.result}}"
        T6-1-2_RESULTS: "${{steps.t6-1-2.outputs.result}}"
        T6-1-3_RESULTS: "${{steps.t6-1-3.outputs.result}}"
        T6-1-4_RESULTS: "${{steps.t6-1-4.outputs.result}}"
      with:
        runners: t6-1-1,t6-1-2,t6-1-3,t6-1-4