name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test11-3-1
      id: test11-3-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test11-3-1
        setup-command: ''
        command: gcc main.c -o main && ./main
        input: |-
          10
          20
          30
          40
          50
        expected-output: |-
          合計値は 150 です。
        comparison-method: exact
        timeout: 1
        max-score: 25
    - name: Test11-3-2
      id: test11-3-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test11-3-2
        setup-command: ''
        command: gcc main.c -o main && ./main
        input: |-
          0
          0
          0
          0
          0
        expected-output: |-
          合計値は 0 です。
        comparison-method: exact
        timeout: 1
        max-score: 25
    - name: Test11-3-3
      id: test11-3-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test11-3-3
        setup-command: ''
        command: gcc main.c -o main && ./main
        input: |-
          -1
          -2
          -3
          -4
          -5
        expected-output: |-
          合計値は -15 です。
        comparison-method: exact
        timeout: 1
        max-score: 25
    - name: Test11-3-4
      id: test11-3-4
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test11-3-4
        setup-command: ''
        command: gcc main.c -o main && ./main
        input: |-
          100
          -50
          200
          -100
          50
        expected-output: |-
          合計値は 200 です。
        comparison-method: exact
        timeout: 1
        max-score: 25
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST11-3-1_RESULTS: "${{steps.test11-3-1.outputs.result}}"
        TEST11-3-2_RESULTS: "${{steps.test11-3-2.outputs.result}}"
        TEST11-3-3_RESULTS: "${{steps.test11-3-3.outputs.result}}"
        TEST11-3-4_RESULTS: "${{steps.test11-3-4.outputs.result}}"
      with:
        runners: test11-3-1,test11-3-2,test11-3-3,test11-3-4